[colors]

  # Выделение
  [colors.selection]
    text = "#111318"
    background = "#a4c9fe"

  # Основная палитра
  [colors.primary]
    background = "#111318"
    foreground = "#e1e2e9"

  [colors.normal]
    black   = "#111318"
    red     = "#f38ba8"
    green   = "#a6e3a1"
    yellow  = "#f9e2af"
    blue    = "#89b4fa"
    magenta = "#9b59b6"
    cyan    = "#94e2d5"
    white   = "#e1e2e9"

  [colors.bright]
    black   = "#1d2024"
    red     = "#f38ba8"
    green   = "#a6e3a1"
    yellow  = "#f9e2af"
    blue    = "#89b4fa"
    magenta = "#9b59b6"
    cyan    = "#94e2d5"
    white   = "#e1e2e9"

  [colors.dim]
    black   = "#0c0e13"
    red     = "#f38ba8"
    green   = "#a6e3a1"
    yellow  = "#f9e2af"
    blue    = "#89b4fa"
    magenta = "#9b59b6"
    cyan    = "#94e2d5"
    white   = "#e1e2e9"

  # # Indexed colors (для 256 цветов)
  # [colors.indexed]
  #   text = "#e1e2e9"
  #   background = "#a4c9fe"
  #
  # # ANSI цвета (для совместимости)
  # [colors.ansi]
  #   black   = "#111318"
  #   red     = "#f38ba8"
  #   green   = "#a6e3a1"
  #   yellow  = "#f9e2af"
  #   blue    = "#89b4fa"
  #   magenta = "#a4c9fe"
  #   cyan    = "#94e2d5"
  #   white   = "#e1e2e9"
  #
  # [colors.ansi_bright]
  #   black   = "#1d2024"
  #   red     = "#f38ba8"
  #   green   = "#a6e3a1"
  #   yellow  = "#f9e2af"
  #   blue    = "#89b4fa"
  #   magenta = "#a4c9fe"
  #   cyan    = "#94e2d5"
  #   white   = "#e1e2e988"
  #
  # [colors.ansi_dim]
  #   black   = "#0c0e13"
  #   red     = "#f38ba8"
  #   green   = "#a6e3a1"
  #   yellow  = "#f9e2af"
  #   blue    = "#89b4fa"
  #   magenta = "#a4c9fe"
  #   cyan    = "#94e2d5"
  #   white   = "#e1e2e988"
