[colors]

  # Выделение
  [colors.selection]
    text = "{{ colors.surface.default.hex }}"
    background = "{{ colors.primary.default.hex }}"

  # Основная палитра
  [colors.primary]
    background = "{{ colors.surface.default.hex }}"
    foreground = "{{ colors.on_surface.default.hex }}"

  [colors.normal]
    black   = "{{ colors.surface.default.hex }}"
    red     = "#f38ba8"
    green   = "#a6e3a1"
    yellow  = "#f9e2af"
    blue    = "#89b4fa"
    magenta = "#9b59b6"
    cyan    = "#94e2d5"
    white   = "{{ colors.on_surface.default.hex }}"

  [colors.bright]
    black   = "{{ colors.surface_container.default.hex }}"
    red     = "#f38ba8"
    green   = "#a6e3a1"
    yellow  = "#f9e2af"
    blue    = "#89b4fa"
    magenta = "#9b59b6"
    cyan    = "#94e2d5"
    white   = "{{ colors.on_surface.default.hex }}"

  [colors.dim]
    black   = "{{ colors.surface_container_lowest.default.hex }}"
    red     = "#f38ba8"
    green   = "#a6e3a1"
    yellow  = "#f9e2af"
    blue    = "#89b4fa"
    magenta = "#9b59b6"
    cyan    = "#94e2d5"
    white   = "{{ colors.on_surface.default.hex }}"

  # # Indexed colors (для 256 цветов)
  # [colors.indexed]
  #   text = "{{ colors.on_surface.default.hex }}"
  #   background = "{{ colors.primary.default.hex }}"
  #
  # # ANSI цвета (для совместимости)
  # [colors.ansi]
  #   black   = "{{ colors.surface.default.hex }}"
  #   red     = "#f38ba8"
  #   green   = "#a6e3a1"
  #   yellow  = "#f9e2af"
  #   blue    = "#89b4fa"
  #   magenta = "{{ colors.primary.default.hex }}"
  #   cyan    = "#94e2d5"
  #   white   = "{{ colors.on_surface.default.hex }}"
  #
  # [colors.ansi_bright]
  #   black   = "{{ colors.surface_container.default.hex }}"
  #   red     = "#f38ba8"
  #   green   = "#a6e3a1"
  #   yellow  = "#f9e2af"
  #   blue    = "#89b4fa"
  #   magenta = "{{ colors.primary.default.hex }}"
  #   cyan    = "#94e2d5"
  #   white   = "{{ colors.on_surface.default.hex }}88"
  #
  # [colors.ansi_dim]
  #   black   = "{{ colors.surface_container_lowest.default.hex }}"
  #   red     = "#f38ba8"
  #   green   = "#a6e3a1"
  #   yellow  = "#f9e2af"
  #   blue    = "#89b4fa"
  #   magenta = "{{ colors.primary.default.hex }}"
  #   cyan    = "#94e2d5"
  #   white   = "{{ colors.on_surface.default.hex }}88"
